# Base Delayed Addition training regime
# This is the configuration used in the baseline training regime.

epochs: 1000
batch_size: 50
optim: rmsprop
lr: 0.0001
l2_norm: 0.0
rate_reg: 0.0
clip: 1.0
early_stopping: False
decay_lr: False
lr_scale: 0.1
lr_decay_patience: 10
keep_hidden: False
